# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "1sfdxq2sn6dv36rin51mwyxgch7pmx9g4yrd5q79lbr7p60484bh";
    x86_64-linux = "0abzj54wrgf73rrlpyjmf0220gn50rwda30rb0la11mgm1fnp89i";
    aarch64-linux = "062i42vd7hb0g7ck980hsbnwh1jx15siw503ykrbvv8ydkj9lmqx";
    x86_64-darwin = "1fm97pm0wzjff8h7pw1f0fiw23icwnmdnq1bziszqajbsy1mynjp";
    aarch64-darwin = "0zwvsa9fsw9pa8m1c6skwmfzzn7lcdhra64xsch3fbh8z0w9brbq";
  };

  urlMap = {
    i686-linux = "https://github.com/lucassabreu/clockify-cli/releases/download/v0.61.0/clockify-cli_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/lucassabreu/clockify-cli/releases/download/v0.61.0/clockify-cli_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/lucassabreu/clockify-cli/releases/download/v0.61.0/clockify-cli_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/lucassabreu/clockify-cli/releases/download/v0.61.0/clockify-cli_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/lucassabreu/clockify-cli/releases/download/v0.61.0/clockify-cli_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "clockify-cli";
  version = "0.61.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./clockify-cli $out/bin/clockify-cli
  '';

  meta = {
    description = "A simple cli to manage your time entries on Clockify from terminal";
    homepage = "https://clockify-cli.netlify.app/";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
