# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "15xdj8haiqbiajmwzyhs4sp1i6bzzi2vqb284axz4myj4nabhqcx";
    x86_64-linux = "0p5ldzlap99bl0mp4fi7npj7ygi5619q9d9jgksi9bj0vm73svp0";
    aarch64-linux = "18cz0x8wzynv1qw1z6mw093dps39xw7qmi50dq2y4im47smmj0qq";
    x86_64-darwin = "1v7z9w0kiszqg4j4xil35fi4jh46p9pqb51b2hq2hbbk7s5d5v1h";
    aarch64-darwin = "0dxlqivlwsyr7v267m58b7s1k2gf2w1rn0m5qv9s33ri3988a70y";
  };

  urlMap = {
    i686-linux = "https://github.com/lucassabreu/clockify-cli/releases/download/v0.61.2/clockify-cli_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/lucassabreu/clockify-cli/releases/download/v0.61.2/clockify-cli_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/lucassabreu/clockify-cli/releases/download/v0.61.2/clockify-cli_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/lucassabreu/clockify-cli/releases/download/v0.61.2/clockify-cli_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/lucassabreu/clockify-cli/releases/download/v0.61.2/clockify-cli_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "clockify-cli";
  version = "0.61.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./clockify-cli $out/bin/clockify-cli
  '';

  meta = {
    description = "A simple cli to manage your time entries on Clockify from terminal";
    homepage = "https://clockify-cli.netlify.app/";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
